<a href="https://colab.research.google.com/github/Aki55755/Batch_21_1422_DS/blob/main/Lab_3_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 import numpy as np
 test_scores = np.random.randint(50, 101, size=(4, 4))
 print(test_scores)

[[77 80 54 62]
 [70 50 59 96]
 [99 89 91 53]
 [54 85 70 51]]


In [ ]:
 column_means = np.mean(test_scores, axis=0)
 row_means = np.mean(test_scores, axis=1)
 print("Column-wise means:", column_means)
 print("Row-wise means:", row_means)

Column-wise means: [75.  76.  68.5 65.5]
Row-wise means: [68.25 68.75 83.   65.  ]


In [ ]:
 std_dev = np.std(test_scores)
 variance = np.var(test_scores)
 print("Standard Deviation:", std_dev)
 print("Variance:", variance)

Standard Deviation: 16.611366590380214
Variance: 275.9375


In [ ]:
 min_value = np.min(test_scores)
 max_value = np.max(test_scores)
 min_index = np.argmin(test_scores)
 max_index = np.argmax(test_scores)
 print("Minimum value:", min_value)
 print("Maximum value:", max_value)
 print("Index of minimum value:", min_index)
 print("Index of maximum value:", max_index)

Minimum value: 50
Maximum value: 99
Index of minimum value: 5
Index of maximum value: 8


In [ ]:
 print("Statistical Analysis Summary:")
 print(f"Row-wise means: {row_means}")
 print(f"Column-wise means: {column_means}")
 print(f"Overall Standard Deviation: {std_dev}")
 print(f"Overall Variance: {variance}")
 print(f"Global Minimum Value: {min_value} (Index: {min_index})")
 print(f"Global Maximum Value: {max_value} (Index: {max_index})")

Statistical Analysis Summary:
Row-wise means: [68.25 68.75 83.   65.  ]
Column-wise means: [75.  76.  68.5 65.5]
Overall Standard Deviation: 16.611366590380214
Overall Variance: 275.9375
Global Minimum Value: 50 (Index: 5)
Global Maximum Value: 99 (Index: 8)


In [ ]:
rgb_image = np.random.randint(0, 256, size=(3, 3, 3))
print(rgb_image)

[[[121  12 150]
  [200 223 105]
  [ 78 143 126]]

 [[253 204 201]
  [139 118   6]
  [ 58 176  58]]

 [[ 31  41  37]
  [ 74  99 109]
  [ 61 210 200]]]


In [ ]:
 red_channel = rgb_image[:, :, 0]
 green_channel = rgb_image[:, :, 1]
 blue_channel = rgb_image[:, :, 2]
 print("Red Channel:\n", red_channel)

Red Channel:
 [[121 200  78]
 [253 139  58]
 [ 31  74  61]]


In [ ]:
 print("Green Channel:\n", green_channel)
 print("Blue Channel:\n", blue_channel)

Green Channel:
 [[ 12 223 143]
 [204 118 176]
 [ 41  99 210]]
Blue Channel:
 [[150 105 126]
 [201   6  58]
 [ 37 109 200]]


In [ ]:
red_mean = np.mean(red_channel)
green_mean = np.mean(green_channel)
blue_mean = np.mean(blue_channel)
print(f"Average pixel intensity for Red channel: {red_mean}")
print(f"Average pixel intensity for Green channel: {green_mean}")
print(f"Average pixel intensity for Blue channel: {blue_mean}")

Average pixel intensity for Red channel: 112.77777777777777
Average pixel intensity for Green channel: 136.22222222222223
Average pixel intensity for Blue channel: 110.22222222222223


In [ ]:
 brightness_increase = 50
 brightened_image = np.clip(rgb_image + brightness_increase, 0, 255)
 print("Brightened Image (clipped at 255):\n", brightened_image)

Brightened Image (clipped at 255):
 [[[171  62 200]
  [250 255 155]
  [128 193 176]]

 [[255 254 251]
  [189 168  56]
  [108 226 108]]

 [[ 81  91  87]
  [124 149 159]
  [111 255 250]]]


In [ ]:
 print("Statistical Analysis Summary:")
 print("Red Channel:\n", red_channel)
 print("Green Channel:\n", green_channel)
 print("Blue Channel:\n", blue_channel)
 print(f"\nAverage pixel intensity for Red channel: {red_mean}")
 print(f"Average pixel intensity for Green channel: {green_mean}")
 print(f"Average pixel intensity for Blue channel: {blue_mean}")
 print("\nBrightened Image (clipped at 255):\n", brightened_image)

Statistical Analysis Summary:
Red Channel:
 [[121 200  78]
 [253 139  58]
 [ 31  74  61]]
Green Channel:
 [[ 12 223 143]
 [204 118 176]
 [ 41  99 210]]
Blue Channel:
 [[150 105 126]
 [201   6  58]
 [ 37 109 200]]

Average pixel intensity for Red channel: 112.77777777777777
Average pixel intensity for Green channel: 136.22222222222223
Average pixel intensity for Blue channel: 110.22222222222223

Brightened Image (clipped at 255):
 [[[171  62 200]
  [250 255 155]
  [128 193 176]]

 [[255 254 251]
  [189 168  56]
  [108 226 108]]

 [[ 81  91  87]
  [124 149 159]
  [111 255 250]]]
